table:
  name: "Products"
  pattern: "products_.*.json"
  primaryKey:
    - product_id
  metadata:
    mode: "FILE"
    format: "JSON"
    write: "APPEND"
  attributes:
    - name: "product_id"
      type: "int"
      required: true
    - name: "name"
      type: "string"
      required: true
    - name: "details"
      type: "struct"
      required: true
      attributes:
        - name: "price"
          type: "double"
          required: true
        - name: "description"
          type: "string"
          required: false
        - name: "category"
          type: "string"
          required: false
    - name: "ingredients"
      type: "struct"
      array: true
      required: true
      attributes:
        - name: "ingredient_id"
          foreignKey: "Ingredients.ingredient_id"
          type: "int"
          required: true
        - name: "quantity"
          type: "double"
          required: true
