---

#validator: "spark" # "spark" (default) or "native"


connectionRef: {{ myConnection }} # default connection ref if not specified in domains / jobs

audit:
  sink:
    connectionRef: {{ myConnection }}
    # database: "project-id" # default to user default project
    # dataset: "audit" # Audit dataset (default to "audit")

connections:
  bigquery:
    type: "bigquery"
    options:
      gcsBucket: "starlake-app"
      authType: "APPLICATION_DEFAULT"
      #authType: SERVICE_ACCOUNT_JSON_KEYFILE
      #jsonKeyfile: "/Users/hayssams/.gcloud/keys/starlake-hayssams.json"

  sparkLocal:
    type: "fs"


