---
table:
  name: "product"
  pattern: "products_.*.json"
  attributes:
  - name: "product_id"
    type: "int"
    array: false
    required: true
    privacy: "NONE"
    ignore: false
  - name: "name"
    type: "string"
    array: false
    required: true
    privacy: "NONE"
    ignore: false
  - name: "price"
    type: "double"
    array: false
    required: true
    privacy: "NONE"
    ignore: false
  - name: "cost"
    type: "double"
    array: false
    required: true
    privacy: "NONE"
    ignore: false
  - name: "description"
    type: "string"
    array: false
    required: false
    privacy: "NONE"
    ignore: false
  - name: "category"
    type: "string"
    array: false
    required: false
    privacy: "NONE"
    ignore: false
  metadata:
    mode: "FILE"
    format: "JSON"
    encoding: "UTF-8"
    multiline: false
    array: false
    withHeader: false
    separator: ""
    quote: "\""
    escape: "\\"
    write: "APPEND"
    sink:
      connectionRef: "{{connectionRef}}"
  primaryKey:
  - "product_id"
