transform:
  default:
    write: OVERWRITE
  taskRefs:
    - most_profitable_products
    - product_performance
    - product_profitability
    - top_selling_products
    - top_selling_profitable_products


