version: '3.7'
services:
  mysql_server:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: starbake
    ports:
      - 3306:3306
    profiles:
      - mysql

  mysql_init_db:
    build:
      context: .
      dockerfile: db_init.DockerFile
    command: python db_init.py mysql
    environment:
      DB_HOSTNAME: mysql_server
    profiles:
      - mysql
    depends_on:
      - mysql_server

  postgres_server:
    image: postgres:latest
    environment:
      POSTGRES_DB: starbake
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    profiles:
      - postgres

  postgres_init_db:
    build:
      context: .
      dockerfile: db_init.DockerFile
    command: python db_init.py postgres
    environment:
      DB_HOSTNAME: postgres_server
    profiles:
      - postgres
    depends_on:
      - postgres_server

  mssql_server:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "01pass_WORD"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    profiles:
      - mssql

  mssql_init_db:
    build:
      context: .
      dockerfile: db_init.DockerFile
    command: python db_init.py mssql
    environment:
      DB_HOSTNAME: mssql_server
    profiles:
      - mssql
    depends_on:
      - mssql_server